// File generated by Antigravity (Manual Config)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM1UePxxPcs1apX_aKFbDjO91MhWw4Dcw',
    appId: '1:817025027842:web:91965eec58e17d44c8bc1b',
    messagingSenderId: '817025027842',
    projectId: 'randevu-app-5984c',
    authDomain: 'randevu-app-5984c.firebaseapp.com',
    storageBucket: 'randevu-app-5984c.firebasestorage.app',
    measurementId: 'G-YT11FFQN7D',
  );

  // For Android/iOS, we use the same keys as placeholders.
  // Ideally, you should download google-services.json / GoogleService-Info.plist
  // But often for simple Auth/Firestore, the API key is enough if not restricted.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM1UePxxPcs1apX_aKFbDjO91MhWw4Dcw',
    appId: '1:817025027842:web:91965eec58e17d44c8bc1b', // Web App ID (Should be Android ID, but placeholder)
    messagingSenderId: '817025027842',
    projectId: 'randevu-app-5984c',
    storageBucket: 'randevu-app-5984c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM1UePxxPcs1apX_aKFbDjO91MhWw4Dcw',
    appId: '1:817025027842:web:91965eec58e17d44c8bc1b', // Web App ID (Should be iOS ID, but placeholder)
    messagingSenderId: '817025027842',
    projectId: 'randevu-app-5984c',
    storageBucket: 'randevu-app-5984c.firebasestorage.app',
    iosBundleId: 'com.example.randevuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM1UePxxPcs1apX_aKFbDjO91MhWw4Dcw',
    appId: '1:817025027842:web:91965eec58e17d44c8bc1b', // Web App ID (Should be macOS ID, but placeholder)
    messagingSenderId: '817025027842',
    projectId: 'randevu-app-5984c',
    storageBucket: 'randevu-app-5984c.firebasestorage.app',
    iosBundleId: 'com.example.randevuApp',
  );
}
